DROP TABLE IF EXISTS EXERCISE;
DROP TABLE IF EXISTS RECORD;

CREATE TABLE RECORD
(
    ID         BIGINT       NOT NULL IDENTITY PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    BODY_PARTS VARCHAR(255) NOT NULL,
);

CREATE TABLE EXERCISE
(
    ID          BIGINT       NOT NULL IDENTITY PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    SERIES      INT          NOT NULL,
    REPETITIONS INT          NOT NULL,
    RECORD_ID   BIGINT       NOT NULL,
);

ALTER TABLE EXERCISE
    ADD CONSTRAINT FK_EXERCICE_RECORD FOREIGN KEY (RECORD_ID) REFERENCES RECORD (ID);