name: gym_tracker
description: Um aplicativo para ajudar a manter o controle de treinos e exercícios.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  go_router: ^6.0.2
  google_fonts: ^4.0.1
  get_it: ^7.2.0
  dio: ^4.0.6
  font_awesome_flutter: ^10.3.0
  flutter_form_builder: ^7.7.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  auto_size_text: ^3.0.0
  multiple_result: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
